# Generated by Django 5.2.4 on 2025-11-20 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0009_auto_20251120_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intento',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
