# Generated by Django 5.2.4 on 2025-12-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
    ]
