# Generated by Django 5.2.4 on 2025-12-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_docente_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='docente',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='accounts.especialidad', verbose_name='Especialidades'),
        ),
    ]
