# Generated by Django 5.2.4 on 2025-12-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_docente_especialidad_docente_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='certification_file',
            field=models.FileField(blank=True, help_text='Certificado o título que acredita la formación como docente', null=True, upload_to='certifications/', verbose_name='Certificado'),
        ),
    ]
